### PR TITLE
Fix build and runtime errors with Dockerfiles

### PR DESCRIPTION
**Pull request by juztamau5**
This PR fixes two build errors and a runtime error that I encountered while following the steps in the README.

First, some rust code was failing to compile with Rust 1.44. Updating to Rust 1.56 fixed the problem. The error was:

```
error[E0658]: use of unstable library feature 'str_strip': newly added
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/impl-serde-0.3.2/src/serialize.rs:97:24
   |
97 |     let (v, stripped) = v.strip_prefix("0x").map_or((v, false), |v| (v, true));
   |                           ^^^^^^^^^^^^
   |
   = note: see issue #67302 <rust-lang/rust#67302> for more information
```

Next, the Alpine images were failing to build because of the removal of the `python` package (replaced with `python3`). The error was:

```
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]
```

Finally, the build succeeded, but during runtime the `ACCOUNT_ADDRESS` environment variable wasn't being set because wagyu couldn't find a version of GCC it was happy with. Updating Debian to bullseye fixed the error. The error was:

```
wagyu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by wagyu)
```

With these changes applied, I was able to run all the examples in the README.

### CODE REVIEW

**Comment by juztamau5** [comment]
ping, anyone able to review and merge this?

**Comment by juztamau5** [comment]
Obsolete with Cartesi Rollups.
